name: Build Navic

on:
  push:
    paths:
      - composeApp/**
      - gradle/**
      - iosApp/**
      - subsonic/**
      - build.gradle.kts
      - settings.gradle.kts
  pull_request:
    paths:
      - composeApp/**
      - gradle/**
      - iosApp/**
      - subsonic/**
      - build.gradle.kts
      - settings.gradle.kts
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_STORE_FILE: ${{ github.workspace }}/release.keystore
          RELEASE: true
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > release.keystore
          ./gradlew :composeApp:packageRelease --stacktrace
          rm release.keystore

      - name: Upload APK artifact
        uses: actions/upload-artifact@v6
        with:
          name: navic-release-android
          path: composeApp/build/outputs/apk/release/*.apk
  build-ipa:
    name: Build iOS IPA
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Theos cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Cache Theos
        id: cache
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Install Theos
        uses: Randomblock1/theos-action@f129528eb3034b088b3eb43f7f935c46ddbdc40c

      - name: Build IPA with Theos
        working-directory: ./iosApp
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          rm -rf packages
          make package

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v6
        with:
          name: navic-release-ios
          path: iosApp/packages/*.ipa
